{"uuid": "bb4733bd-9975-4b91-b8df-87175ad96b10", "children": ["9a9d0484-96d5-422d-8923-8227292e3ca8", "2b765589-8c46-45b3-976d-042f72af813e", "d16403f8-3a34-49f0-b0ba-26ded932e0d7", "c62d33b1-ba7a-4425-8542-e8d0772604bc", "bf0775a4-38f8-4635-8213-af061c68f3b8", "0111cb72-b402-46a7-aaca-e44ca16b6eaf"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=134.0.6998.90)\nStacktrace:\n\tGetHandleVerifier [0x00007FF791E9FE65+26629]\n\t(No symbol) [0x00007FF791E06030]\n\t(No symbol) [0x00007FF791C9931A]\n\t(No symbol) [0x00007FF791C95D10]\n\t(No symbol) [0x00007FF791C868C9]\n\t(No symbol) [0x00007FF791C88638]\n\t(No symbol) [0x00007FF791C86BD6]\n\t(No symbol) [0x00007FF791C86656]\n\t(No symbol) [0x00007FF791C8631A]\n\t(No symbol) [0x00007FF791C83E9F]\n\t(No symbol) [0x00007FF791C8478C]\n\t(No symbol) [0x00007FF791C9D16A]\n\t(No symbol) [0x00007FF791D4102E]\n\t(No symbol) [0x00007FF791D17AAA]\n\t(No symbol) [0x00007FF791D40169]\n\t(No symbol) [0x00007FF791D17883]\n\t(No symbol) [0x00007FF791CE0550]\n\t(No symbol) [0x00007FF791CE1803]\n\tGetHandleVerifier [0x00007FF7921F72DD+3529853]\n\tGetHandleVerifier [0x00007FF79220DA42+3621858]\n\tGetHandleVerifier [0x00007FF7922024F3+3575443]\n\tGetHandleVerifier [0x00007FF791F6B79A+860474]\n\t(No symbol) [0x00007FF791E108AF]\n\t(No symbol) [0x00007FF791E0CBE4]\n\t(No symbol) [0x00007FF791E0CD86]\n\t(No symbol) [0x00007FF791DFC2E9]\n\tBaseThreadInitThunk [0x00007FFEE8F2E8D7+23]\n\tRtlUserThreadStart [0x00007FFEE957BF6C+44]\n\n", "trace": "  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\tests\\test_report_panel_checks.py\", line 32, in setup\n    driver = browser.way1(URL)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\utilities\\browser_setup.py\", line 37, in way1\n    self.driver.get(url)\n    ~~~~~~~~~~~~~~~^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742494130717, "stop": 1742494137452}], "start": 1742494130717, "stop": 1742494137695}