{"uuid": "ec35787f-e9cb-4744-9331-8ed66d15ce98", "children": ["3f48791a-8d45-4a2f-9276-36b6f8e720c1", "a49a8ef0-fe10-40dc-8d66-b403e19cc493", "46e6fedc-3acd-4e17-ab8e-da6065b3ee15", "08172dcb-730b-4733-9907-cf5c2b39c1df", "649df22e-afc2-439c-9003-6814d14a8a12", "3198085f-a359-4df6-9250-bf4333d4bc91"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=134.0.6998.90)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7D324FE65+26629]\n\t(No symbol) [0x00007FF7D31B6030]\n\t(No symbol) [0x00007FF7D304931A]\n\t(No symbol) [0x00007FF7D3045D10]\n\t(No symbol) [0x00007FF7D30368C9]\n\t(No symbol) [0x00007FF7D3038638]\n\t(No symbol) [0x00007FF7D3036BD6]\n\t(No symbol) [0x00007FF7D3036656]\n\t(No symbol) [0x00007FF7D303631A]\n\t(No symbol) [0x00007FF7D3033E9F]\n\t(No symbol) [0x00007FF7D303478C]\n\t(No symbol) [0x00007FF7D304D16A]\n\t(No symbol) [0x00007FF7D30F102E]\n\t(No symbol) [0x00007FF7D30C7AAA]\n\t(No symbol) [0x00007FF7D30F0169]\n\t(No symbol) [0x00007FF7D30C7883]\n\t(No symbol) [0x00007FF7D3090550]\n\t(No symbol) [0x00007FF7D3091803]\n\tGetHandleVerifier [0x00007FF7D35A72DD+3529853]\n\tGetHandleVerifier [0x00007FF7D35BDA42+3621858]\n\tGetHandleVerifier [0x00007FF7D35B24F3+3575443]\n\tGetHandleVerifier [0x00007FF7D331B79A+860474]\n\t(No symbol) [0x00007FF7D31C08AF]\n\t(No symbol) [0x00007FF7D31BCBE4]\n\t(No symbol) [0x00007FF7D31BCD86]\n\t(No symbol) [0x00007FF7D31AC2E9]\n\tBaseThreadInitThunk [0x00007FFEE8F2E8D7+23]\n\tRtlUserThreadStart [0x00007FFEE957BF6C+44]\n\n", "trace": "  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\tests\\test_report_panel_checks.py\", line 32, in setup\n    driver = browser.way1(URL)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\utilities\\browser_setup.py\", line 37, in way1\n    self.driver.get(url)\n    ~~~~~~~~~~~~~~~^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742479076320, "stop": 1742479082931}], "start": 1742479076320, "stop": 1742479083148}