{"uuid": "9e057071-eb59-4c02-8af7-729f5f380e89", "children": ["7e903a6d-ac61-4beb-b722-1650be1dac40", "7bafde54-3c7b-4114-b807-f1fe7511aed9", "37f42961-d3d9-4c61-b4e1-5dff6d487a35", "61e127df-c8d5-4113-88ab-12f564fe0155", "df757468-a07d-4668-9ca7-0a08d5cd1e43", "ca1b90aa-0750-43e7-8a02-f643316639be", "570916f0-8c85-4a70-ab90-777b8b07abb5"], "befores": [{"name": "setup_teardown_qi_exerciser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=134.0.6998.90)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7D324FE65+26629]\n\t(No symbol) [0x00007FF7D31B6030]\n\t(No symbol) [0x00007FF7D304931A]\n\t(No symbol) [0x00007FF7D3045D10]\n\t(No symbol) [0x00007FF7D30368C9]\n\t(No symbol) [0x00007FF7D3038638]\n\t(No symbol) [0x00007FF7D3036BD6]\n\t(No symbol) [0x00007FF7D3036656]\n\t(No symbol) [0x00007FF7D303631A]\n\t(No symbol) [0x00007FF7D3033E9F]\n\t(No symbol) [0x00007FF7D303478C]\n\t(No symbol) [0x00007FF7D304D16A]\n\t(No symbol) [0x00007FF7D30F102E]\n\t(No symbol) [0x00007FF7D30C7AAA]\n\t(No symbol) [0x00007FF7D30F0169]\n\t(No symbol) [0x00007FF7D30C7883]\n\t(No symbol) [0x00007FF7D3090550]\n\t(No symbol) [0x00007FF7D3091803]\n\tGetHandleVerifier [0x00007FF7D35A72DD+3529853]\n\tGetHandleVerifier [0x00007FF7D35BDA42+3621858]\n\tGetHandleVerifier [0x00007FF7D35B24F3+3575443]\n\tGetHandleVerifier [0x00007FF7D331B79A+860474]\n\t(No symbol) [0x00007FF7D31C08AF]\n\t(No symbol) [0x00007FF7D31BCBE4]\n\t(No symbol) [0x00007FF7D31BCD86]\n\t(No symbol) [0x00007FF7D31AC2E9]\n\tBaseThreadInitThunk [0x00007FFEE8F2E8D7+23]\n\tRtlUserThreadStart [0x00007FFEE957BF6C+44]\n\n", "trace": "  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\tests\\test_Qi_Exerciser_checks.py\", line 73, in setup_teardown_qi_exerciser\n    driver = browser.way1(URL)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\utilities\\browser_setup.py\", line 37, in way1\n    self.driver.get(url)\n    ~~~~~~~~~~~~~~~^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742478958132, "stop": 1742478964795}], "start": 1742478958132, "stop": 1742478965117}