{"uuid": "e9cfec80-2eea-4840-b0df-6e7e8ec13d02", "children": ["9a11e20e-b41c-44fd-b717-1ec956e6eb56", "4dd01dc1-a997-42f9-b4c6-fe2ac29b769a", "a0ca09c0-e098-49fa-b30c-356b4ab18cab", "0f67525a-b1c0-45b6-b21f-9e099a3c7578", "befc418a-23fe-4811-a642-bb2dc4784496", "a03062de-25ed-4614-85d6-8a86d15454fd", "cb3c64b1-5412-438c-b58b-08bd9da8c791"], "befores": [{"name": "setup_teardown_qi_exerciser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=134.0.6998.90)\nStacktrace:\n\tGetHandleVerifier [0x00007FF791E9FE65+26629]\n\t(No symbol) [0x00007FF791E06030]\n\t(No symbol) [0x00007FF791C9931A]\n\t(No symbol) [0x00007FF791C95D10]\n\t(No symbol) [0x00007FF791C868C9]\n\t(No symbol) [0x00007FF791C88638]\n\t(No symbol) [0x00007FF791C86BD6]\n\t(No symbol) [0x00007FF791C86656]\n\t(No symbol) [0x00007FF791C8631A]\n\t(No symbol) [0x00007FF791C83E9F]\n\t(No symbol) [0x00007FF791C8478C]\n\t(No symbol) [0x00007FF791C9D16A]\n\t(No symbol) [0x00007FF791D4102E]\n\t(No symbol) [0x00007FF791D17AAA]\n\t(No symbol) [0x00007FF791D40169]\n\t(No symbol) [0x00007FF791D17883]\n\t(No symbol) [0x00007FF791CE0550]\n\t(No symbol) [0x00007FF791CE1803]\n\tGetHandleVerifier [0x00007FF7921F72DD+3529853]\n\tGetHandleVerifier [0x00007FF79220DA42+3621858]\n\tGetHandleVerifier [0x00007FF7922024F3+3575443]\n\tGetHandleVerifier [0x00007FF791F6B79A+860474]\n\t(No symbol) [0x00007FF791E108AF]\n\t(No symbol) [0x00007FF791E0CBE4]\n\t(No symbol) [0x00007FF791E0CD86]\n\t(No symbol) [0x00007FF791DFC2E9]\n\tBaseThreadInitThunk [0x00007FFEE8F2E8D7+23]\n\tRtlUserThreadStart [0x00007FFEE957BF6C+44]\n\n", "trace": "  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\tests\\test_Qi_Exerciser_checks.py\", line 73, in setup_teardown_qi_exerciser\n    driver = browser.way1(URL)\n  File \"C:\\Users\\GRL\\PycharmProjects\\25W automation\\Project-24\\utilities\\browser_setup.py\", line 37, in way1\n    self.driver.get(url)\n    ~~~~~~~~~~~~~~~^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\GRL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742494010684, "stop": 1742494019294}], "start": 1742494010684, "stop": 1742494019691}